// Auto-generated by scripts/split-bible-chunks.mjs — do not edit by hand.
export const packedBibleChunks: Array<number | { uri: string }> = [
  require('../../assets/bible/chunks/00.txt'), // 0
  require('../../assets/bible/chunks/01.txt'), // 1
  require('../../assets/bible/chunks/02.txt'), // 2
  require('../../assets/bible/chunks/03.txt'), // 3
  require('../../assets/bible/chunks/04.txt'), // 4
  require('../../assets/bible/chunks/05.txt'), // 5
  require('../../assets/bible/chunks/06.txt'), // 6
  require('../../assets/bible/chunks/07.txt'), // 7
  require('../../assets/bible/chunks/08.txt'), // 8
];
